add bin to hex conversion

diff --git a/src/nconv b/src/nconv
--- a/src/nconv
+++ b/src/nconv
@@ -168,13 +168,13 @@ is_bin_num() {
 # PARAMETERS:
 #   $1 - number
 is_dec_num() {
-    echo "$1" | grep -qE '^-?[[:digit:]]+$'
+    echo "$1" | grep -qE '^-?[0123456789]+$'
 }
 
 # PARAMETERS:
 #   $1 - number
 is_hex_num() {
-    echo "$1" | grep -qE '^(0x|0X|)[[:xdigit:]]+$'
+    echo "$1" | grep -qE '^[0123456789ABCDEF]+$'
 }
 
 #-------------------------------------------------------------------------------
@@ -257,9 +257,18 @@ bin_to_dec() (
 
 # PARAMETERS:
 #   $1 - binary number
-bin_to_hex() {
-    echo "bin_to_hex $1"
-}
+bin_to_hex() (
+    bin_num="$(canonical_bin "$1")" &&
+    hex_num="$(echo "obase=16; ibase=2; $bin_num" | bc)" &&
+    if [ "$input_sign" = signed ]; then
+        target_msb="$(echo "$bin_num" | cut -c 1)" &&
+        hex_num="$(adjust_hex_sign "$hex_num" "$target_msb")"
+    fi &&
+    if [ "$output_width" ]; then
+        hex_num="$(extend_chex "$hex_num")"
+    fi &&
+    echo "$hex_num"
+)
 
 # PARAMETERS:
 #   $1 - binary number
@@ -358,6 +367,43 @@ hex_to_dec() {
 hex_to_hex() {
     echo "hex_to_hex $1"
 }
+
+# PARAMETERS:
+#   $1 - canonical hexadecimal number
+#   $2 - target most significant bit
+adjust_hex_sign() (
+    left_digit="$(echo "$1" | cut -c 1)" &&
+    case "$2" in
+        0)  case "$left_digit" in [8-9] | [A-F]) # negative -> positive
+                left_digit="0$left_digit" ;;
+            esac ;;
+        1)  case "$left_digit" in # positive -> negative
+                1 | 3 | 7) left_digit=F ;;
+                2 | 6) left_digit=E ;;
+                4) left_digit=C ;;
+                5) left_digit=D ;;
+            esac ;;
+    esac &&
+    echo "$left_digit${1#?}"
+)
+
+# PARAMETERS:
+#   $1 - canonical hexadecimal number
+extend_chex() (
+    extend_by="$((output_width - ${#1}))" &&
+    if [ "$extend_by" -ge 0 ]; then
+        extend_digit=0
+        if [ "$input_sign" = signed ]; then
+            case "$1" in [8-9]* | [A-F]*)
+                extend_digit=F ;;
+            esac
+        fi &&
+        extend_digits="$(clone_char "$extend_digit" "$extend_by")"
+        echo "$extend_digits$1"
+    else
+        echo "could not fit $1 into $output_width digits" >&2; return 1
+    fi
+)
 
 #-------------------------------------------------------------------------------
 # CALL MAIN
